services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "13"
      DISK_SIZE: "256G"
      ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234"
    devices:
      # - /dev/kvm           # Commented out: KVM not supported on this CPU
      - /dev/net/tun
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
      - ./example:/shared
    restart: always
    stop_grace_period: 2m