version: '3'

volumes:
  www-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUME}/html
  openssh-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUME}/openssh

services:
  sshd:
    image: hermsi/alpine-sshd
    volumes:
      - www-data:/var/www/html
      - openssh-data:/etc/ssh
      - ./travis_id_rsa.pub:/conf.d/authorized_keys/travis
    environment:
      - DEBUG=${DEBUG}
      - SSH_USERS=${SSH_USERS}
    ports:
      - "${SSH_PORT}:22"
    networks:
      - default

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - www-data:/var/www/html
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - default
      - nginxproxy

networks:
  nginxproxy:
    external:
      name: ${NGINXPROXYNETWORK}