version: '3.8'

services:
  kasmweb:
    image: kasmweb/core:latest
    container_name: kasmweb
    restart: unless-stopped
    ports:
      - "6901:6901"  # Web access port
    environment:
      - KASM_DB_HOST=db
      - KASM_REDIS_HOST=redis
      - KASM_DB_USER=kasmuser
      - KASM_DB_PASSWORD=kasm_password
      - KASM_DB_NAME=kasmdb
    depends_on:
      - db
      - redis
    volumes:
      - kasm_data:/opt/kasm/current/data

  db:
    image: postgres:13-alpine
    container_name: kasm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kasmuser
      POSTGRES_PASSWORD: kasm_password
      POSTGRES_DB: kasmdb
    volumes:
      - kasm_db_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: kasm_redis
    restart: unless-stopped
    volumes:
      - kasm_redis_data:/data

volumes:
  kasm_data:
  kasm_db_data:
  kasm_redis_data:
